server.port=8081

spring.application.name=starter-demo
spring.datasource.url=jdbc:mysql://localhost:3306/dog_day
spring.datasource.username=root
spring.datasource.password=4200
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
notification.service.base-url=http://localhost:8081
logging.file.name=logs/app.log
logging.level.root=INFO